/**
 * ReceiptService - Generates PDF receipts and exports transaction history
 * Part of Nexar - Next-Gen Stellar Payments
 */

import jsPDF from 'jspdf'
import QRCode from 'qrcode'
import Papa from 'papaparse'
import JSZip from 'jszip'

export interface Receipt {
  id: string
  transactionHash: string
  from: string
  to: string
  amount: number
  currency: string
  timestamp: number
  note?: string
  status: 'success' | 'failed'
}

export class ReceiptService {
  /**
   * Generate a PDF receipt for a transaction
   */
  async generateReceipt(receipt: Receipt, note?: string): Promise<Blob> {
    const doc = new jsPDF()
    
    // Header
    doc.setFontSize(24)
    doc.setTextColor(99, 102, 241) // Stellar blue
    doc.text('Nexar', 20, 20)
    
    doc.setFontSize(16)
    doc.setTextColor(0, 0, 0)
    doc.text('Payment Receipt', 20, 35)
    
    // Receipt details
    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text(`Receipt #${receipt.id}`, 20, 45)
    doc.text(`Date: ${new Date(receipt.timestamp).toLocaleString()}`, 20, 52)
    
    // Divider
    doc.setDrawColor(200, 200, 200)
    doc.line(20, 58, 190, 58)
    
    // Transaction details
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    
    doc.text('From:', 20, 70)
    doc.setFont(undefined, 'normal')
    doc.text(receipt.from, 50, 70)
    
    doc.setFont(undefined, 'bold')
    doc.text('To:', 20, 80)
    doc.setFont(undefined, 'normal')
    doc.text(receipt.to, 50, 80)
    
    doc.setFont(undefined, 'bold')
    doc.text('Amount:', 20, 90)
    doc.setFont(undefined, 'normal')
    doc.setFontSize(16)
    doc.text(`${receipt.amount} ${receipt.currency}`, 50, 90)
    
    doc.setFontSize(12)
    doc.setFont(undefined, 'bold')
    doc.text('Status:', 20, 100)
    doc.setFont(undefined, 'normal')
    doc.setTextColor(receipt.status === 'success' ? 0 : 255, receipt.status === 'success' ? 128 : 0, 0)
    doc.text(receipt.status.toUpperCase(), 50, 100)
    
    // Note
    if (note || receipt.note) {
      doc.setTextColor(0, 0, 0)
      doc.setFont(undefined, 'bold')
      doc.text('Note:', 20, 110)
      doc.setFont(undefined, 'normal')
      const noteText = note || receipt.note || ''
      const splitNote = doc.splitTextToSize(noteText, 160)
      doc.text(splitNote, 20, 118)
    }
    
    // Transaction hash
    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text('Transaction Hash:', 20, 140)
    doc.setFont(undefined, 'normal')
    doc.text(receipt.transactionHash, 20, 147)
    
    // Generate QR code
    const stellarExpertUrl = `https://stellar.expert/explorer/testnet/tx/${receipt.transactionHash}`
    const qrDataUrl = await QRCode.toDataURL(stellarExpertUrl, { width: 100 })
    doc.addImage(qrDataUrl, 'PNG', 150, 130, 40, 40)
    
    doc.setFontSize(8)
    doc.text('Scan to verify on', 145, 175)
    doc.text('Stellar Expert', 148, 180)
    
    // Footer
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text('This receipt is generated by Nexar', 20, 280)
    doc.text('Next-Gen Stellar Payments - Verify on blockchain', 20, 285)
    
    return doc.output('blob')
  }
  
  /**
   * Generate multiple receipts as a ZIP file
   */
  async generateBulkReceipts(receipts: Receipt[]): Promise<Blob> {
    const zip = new JSZip()
    
    for (const receipt of receipts) {
      const pdf = await this.generateReceipt(receipt)
      const filename = `receipt_${receipt.id}_${receipt.transactionHash.substring(0, 8)}.pdf`
      zip.file(filename, pdf)
    }
    
    return await zip.generateAsync({ type: 'blob' })
  }
  
  /**
   * Export transactions to CSV
   */
  exportToCSV(receipts: Receipt[]): Blob {
    const data = receipts.map(r => ({
      'Receipt ID': r.id,
      'Transaction Hash': r.transactionHash,
      'From': r.from,
      'To': r.to,
      'Amount': r.amount,
      'Currency': r.currency,
      'Date': new Date(r.timestamp).toLocaleString(),
      'Status': r.status,
      'Note': r.note || ''
    }))
    
    const csv = Papa.unparse(data)
    return new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  }
  
  /**
   * Export transactions to JSON
   */
  exportToJSON(receipts: Receipt[]): Blob {
    const json = JSON.stringify(receipts, null, 2)
    return new Blob([json], { type: 'application/json' })
  }
  
  /**
   * Generate a comprehensive PDF report
   */
  async exportToPDF(receipts: Receipt[]): Promise<Blob> {
    const doc = new jsPDF()
    
    // Title
    doc.setFontSize(20)
    doc.text('Transaction History Report', 20, 20)
    
    doc.setFontSize(10)
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 30)
    doc.text(`Total Transactions: ${receipts.length}`, 20, 37)
    
    // Calculate totals
    const totalAmount = receipts.reduce((sum, r) => sum + r.amount, 0)
    doc.text(`Total Amount: ${totalAmount.toFixed(2)} XLM`, 20, 44)
    
    // Table header
    let y = 55
    doc.setFontSize(9)
    doc.setFont(undefined, 'bold')
    doc.text('Date', 20, y)
    doc.text('Amount', 70, y)
    doc.text('To', 110, y)
    doc.text('Status', 170, y)
    
    // Table rows
    doc.setFont(undefined, 'normal')
    y += 7
    
    receipts.forEach((receipt, index) => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      
      const date = new Date(receipt.timestamp).toLocaleDateString()
      doc.text(date, 20, y)
      doc.text(`${receipt.amount} ${receipt.currency}`, 70, y)
      doc.text(receipt.to.substring(0, 15) + '...', 110, y)
      doc.text(receipt.status, 170, y)
      
      y += 7
    })
    
    return doc.output('blob')
  }
  
  /**
   * Download a blob as a file
   */
  downloadBlob(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }
  
  /**
   * Share receipt (generate shareable URL)
   */
  shareReceipt(receiptId: string): string {
    // Store receipt in localStorage for sharing
    const shareKey = `shared_receipt_${receiptId}`
    const receipt = localStorage.getItem(`receipt_${receiptId}`)
    if (receipt) {
      localStorage.setItem(shareKey, receipt)
    }
    
    // Generate shareable URL
    return `${window.location.origin}/receipt/${receiptId}`
  }
  
  /**
   * Get shared receipt
   */
  getSharedReceipt(receiptId: string): Receipt | null {
    const data = localStorage.getItem(`shared_receipt_${receiptId}`)
    return data ? JSON.parse(data) : null
  }
}

// Export singleton instance
export const receiptService = new ReceiptService()
